project:
  type: website

website:
  title: "Test site"
  navbar:
    left:
      - text: Home
        href: index.md

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
