[project]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
name = "quarto-test"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
quarto = ">=1.7.30,<2"

[tasks]
preview = "quarto preview"
render = "quarto render"
